# Generated by Django 4.2 on 2023-04-28 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Booking'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name': 'Report'},
        ),
        migrations.AlterModelOptions(
            name='stockin',
            options={'verbose_name': 'StockIn', 'verbose_name_plural': 'StockIn'},
        ),
        migrations.AlterModelOptions(
            name='stockout',
            options={'verbose_name': 'StockOut', 'verbose_name_plural': 'StockOut'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Type'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterModelOptions(
            name='usersrole',
            options={'verbose_name': 'UsersRole', 'verbose_name_plural': 'UserRole'},
        ),
        migrations.AlterModelOptions(
            name='vendors',
            options={'verbose_name': 'Vendor'},
        ),
        migrations.RemoveField(
            model_name='types',
            name='items',
        ),
        migrations.AddField(
            model_name='items',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='amount',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='items',
            name='fine',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='items',
            name='gross_weight',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='items',
            name='labour_wastage',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='items',
            name='net_weight',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='items',
            name='purity',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usersrole',
            name='billing',
            field=models.IntegerField(default=0),
        ),
    ]
