# Generated by Django 4.2 on 2023-04-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_booking_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrole',
            name='billing',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usersrole',
            name='sale',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond')], max_length=100),
        ),
    ]
