# Generated by Django 4.2 on 2023-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_usersrole_billing_alter_usersrole_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
